### ISSUE TITLE
Image file is locked until VS Code is closed

### ISSUE THREAD

**Issue by derrickb** [kisstkondoros/gutter-preview#14]
Hi, ran into an interesting bug while iterating on images for my app.

If I hover over an image and thus bring up the preview, and then attempt to save over the source file with Photoshop, I will get an error that the filename is invalid (even after the hover preview is gone).  I'll also be unable to delete the file as it will appear locked.

Closing VS Code will release the lock so I can delete it or save over it, however if I reopen Code and bring up the hover preview again, it will again lock the file.

Windows 10 x64, VS Code 1.17.2, gutter-preview 1.11.4

**Comment by kisstkondoros** [comment]
This is indeed strange.
I've tried to reproduce it without success (however I have Linux at the moment, and no photoshop)

I'll have a look into this during the weekend.

Also I've found another issue in connection with this:
since the vscode (electron -> chrome) caches the images, it is basically impossible to have an up to date preview after an image has been loaded.
I'm currently working on a possible solution for this, which will eventually solve the mentioned issue for sure, but it'll take some time.

Please be patient and thanks for reporting the bug.

**Comment by kisstkondoros** [comment]
Version 1.12.0 is in the market, fix included :fireworks:
