### ISSUE TITLE
Feature Request: Preview images in output channel?

### ISSUE THREAD

**Issue by Gruntfuggly** [kisstkondoros/gutter-preview#18]
Is it possible to extend this so that urls shown in an output channel can be shown too?

I put some debug into the extension and I could see that it was activating the hover provider for the output channel, but I assume it hasn't been able to find the URL and generate an image for it.

**Comment by kisstkondoros** [comment]
Thanks for the issue report!

The problem was exactly what you've described, but tackling it took a while :weary: 

Version v0.14.0 is in the market with a lot of good stuff, amongs others: more flexible link resolution (this was the problem with the output channel). :fireworks: 

If you encounter an issue with the new version, please don't hesitate to create a new issue.

**Comment by Gruntfuggly** [comment]
Brilliant - thanks!

Now this works, I hope you don't mind if I include your extension as a dependency of one of mine. It uses the output window for a chat channel and shows images as URLS, which now show up thanks to your extension. :grin:

**Comment by kisstkondoros** [comment]
Neat!
