### ISSUE TITLE
Maybe preview like Brackets does?

### ISSUE THREAD

**Issue by Madebym** [kisstkondoros/gutter-preview#4]
Have you seen the way Brackets handles image previews? When you hover over the image path(both HTML and CSS) a nice popup appears with image in original dimensions, if it is too big, then it is rezised.

Gutter preview is really nice, but apart from icons, other images are really small, basically I can't see the image previewed, all blurred and small.

If it is any help, here is the repo for that extension(later it was added to Brackets core) https://github.com/gruehle/HoverPreview

**Comment by kisstkondoros** [comment]
Hi,

I just had a deeper look into this.
A similar functionality already exists, but due to the current VSCode API limitations it only supports a very limited markdown syntax to provide the hover content.
Moreover the markdown processor they use ( [https://github.com/chjj/marked](marked) ) does not supports image resizing without some additional configuration (which I can not do from an extension).

So I'm afraid I can't do anything about it currently.

**Comment by kisstkondoros** [comment]
Feature request issued for this in the vscode repo:
https://github.com/Microsoft/vscode/issues/14803

**Comment by kisstkondoros** [comment]
Just published v0.7.2, is in the market.
Using that and vscode version 1.8 ( insider preview ) and above should provide a better experience.

**Comment by Madebym** [comment]
Great, I'll give it a try !

**Comment by Madebym** [comment]
Excellent work !

Is it possible to have an option to remove the initial left-sided gutter preview, and only have the popup available?

Thanks

**Comment by kisstkondoros** [comment]
Version 0.8.1 is in the market!
By using the following setting, the preview on the gutter can be disabled:
```json
"gutterpreview.showimagepreviewongutter": false
```
(reopening the text editors might be necessary to take effect)

**Comment by Madebym** [comment]
Super nice!  Thanks for the quick implementation. 

The way it is functioning now, I believe that it is much better way to preview images, than just having gutter side preview.
