### ISSUE TITLE
Support Steam Image URL's

### ISSUE THREAD

**Issue by SupinePandora43** [kisstkondoros/gutter-preview#51]
like
```
https://steamuserimages-a.akamaihd.net/ugc/269465369197223851/44A5D3F3131F2EED3BB179D14753E11EADE43DAB/
```

**Comment by kisstkondoros** [comment]
The problem is that the url does not contain anything to be "sure" that it points to an image. Without this check every url in the active editor would be downloaded, which is definitely not wanted. Adding an exception to this rule to steamuserimages or google photos would be also unacceptable IMO.

Sorry. :(

**Comment by SupinePandora43** [comment]
@kisstkondoros  how can be setted url checking regex?!

**Comment by kisstkondoros** [comment]
@SupinePandora43 Could you please rephrase the question, I don't understand it.

**Comment by SupinePandora43** [comment]
@kisstkondoros  how can i provide custom regular expression for allowing preview

**Comment by kisstkondoros** [comment]
It is not an option at the moment.

**Comment by SupinePandora43** [comment]
@kisstkondoros  may be create "feature-request" issue
