### ISSUE TITLE
Feature Request: Missing image on path icon

### ISSUE THREAD

**Issue by Denis-net** [kisstkondoros/gutter-preview#68]
Good day @kisstkondoros 
First of all:
Thank you for the great extension, 
with that Visual Studio Code is a better place.

I was very busy but today I want to expose you an idea that i had time ago:
Could be possible to add an option `gutterpreview.showMissingImageOnPathIcon`, which shows a missing icon where a file is expected but not found ?
![image](https://icon-library.net/images/not-found-icon/not-found-icon-18.jpg)
or (404)

(optional) a treelist that lists all the missing image paths and allows to jump to unresolvable path in code.

Thanks anyway 😊👍🏻

**Comment by kisstkondoros** [comment]
Sorry for the late response.

The way how this extension detects image paths tries to be language and framework independent, therefore it is full of regexp based matchers.
Due to this (flawed design) false positives and missing images can not be distinguished, therefore such an option is not doable based on the current implementation.
